<?xml version="1.0" ?>
<!--       simulation model of crawler robot in UGVC 2016         -->
<robot name="ugvc_crawler_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="$(find ugvc_description)/urdf/ugvc_crawler_robot.gazebo.xacro" />

	<xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="chassis_mass" value="20" /> <!-- arbitrary value for mass -->
  <xacro:property name="wheel_mass" value="3" />
  <xacro:property name="flipper_mass" value="3" />

  <xacro:property name="chassis_width" value="0.32" />
  <xacro:property name="chassis_length" value="0.58" />
  <xacro:property name="chassis_thickness" value="0.1" />

  <xacro:property name="flipper_length" value="0.37" />
  <xacro:property name="flipper_width" value="0.1" />
  <xacro:property name="flipper_thickness" value="0.02" />


  <xacro:property name="wheel_radius" value="0.065" />
  <xacro:property name="main_wheel_length" value="0.12" />
  <xacro:property name="flipper_wheel_length" value="0.06" />

  <xacro:macro name="kylin_robot">

  <link name="chassis">
    <inertial>
      <mass value="${chassis_mass}"/>
      <origin rpy="0  0  0" xyz="0 0 ${wheel_radius}"/>
      <inertia ixx="10" ixy="0" ixz="0" iyy="10" iyz="0" izz="10"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0  0  0" xyz="0 0 ${wheel_radius}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_thickness}"/>
      </geometry>
    </collision>
    <visual name="visual_chassis">
      <origin rpy="0  0  0" xyz="0 0 ${wheel_radius}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_thickness}"/>
      </geometry>
    </visual>

    <!--
    <visual name="left_crawler_visual">
        <origin rpy="${PI/2}  0  ${PI/2}" xyz="${-chassis_width/2-main_wheel_length} ${-chassis_length/2} ${wheel_radius}"/>
        <geometry>
          <mesh filename="package://ugvc_description/meshes/main_crawler.dae" />
        </geometry>
      </visual>

      <visual name="right_crawler_visual">
        <origin rpy="${-PI/2}  0  ${PI/2}" xyz="${chassis_width/2+main_wheel_length} ${-chassis_length/2} ${wheel_radius}"/>
        <geometry>
          <mesh filename="package://ugvc_description/meshes/main_crawler.dae" />
        </geometry>
      </visual>

    -->
  </link>

  <joint name="right_main_front_wheel" type="continuous">
    <parent link="chassis"/>
    <child link="right_main_front_wheel"/>
    <origin rpy="0 0 0" xyz="${chassis_length/2} ${-chassis_width/2-main_wheel_length/2}  ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

   <link name="right_main_front_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
     <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <inertia ixx="0.02467" ixy="0" ixz="0" iyy="0.02467" iyz="0" izz="0.04411"/>
    </inertial>
    <collision name="collision">
      <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

  </link>

  <joint name="left_main_front_wheel" type="continuous">
    <parent link="chassis"/>
    <child link="left_main_front_wheel"/>
    <origin rpy="0 0 0" xyz="${chassis_length/2} ${chassis_width/2+main_wheel_length/2} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

   <link name="left_main_front_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <inertia ixx="0.02467" ixy="0" ixz="0" iyy="0.02467" iyz="0" izz="0.04411"/>
    </inertial>
    <collision name="collision">
      <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

  </link>

  <joint name="right_main_rear_wheel" type="continuous">
    <parent link="chassis"/>
    <child link="right_main_rear_wheel"/>
    <origin rpy="0 0 0" xyz="${-chassis_length/2} ${-chassis_width/2-main_wheel_length/2}  ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

   <link name="right_main_rear_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <inertia ixx="0.02467" ixy="0" ixz="0" iyy="0.02467" iyz="0" izz="0.04411"/>
    </inertial>
    <collision name="collision">
      <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

  </link>

  <joint name="left_main_rear_wheel" type="continuous">
    <parent link="chassis"/>
    <child link="left_main_rear_wheel"/>
    <origin rpy="0 0 0" xyz="${-chassis_length/2} ${chassis_width/2+main_wheel_length/2}  ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

   <link name="left_main_rear_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <inertia ixx="0.02467" ixy="0" ixz="0" iyy="0.02467" iyz="0" izz="0.04411"/>
    </inertial>
    <collision name="collision">
      <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <visual name="visual">
      <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

  </link>

      <!-- IMU Link is the standard mounting position for the UM6 IMU.-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
      <origin xyz="$(optenv KYLIN_IMU_XYZ 0 0 0.05)" rpy="$(optenv KYLIN_IMU_RPY 0 -1.5708 3.1416)" />
      <parent link="chassis" />
      <child link="imu_link" />
    </joint>
    <gazebo reference="imu_link">
    </gazebo>



<!-- by Kong 
  <joint name="right_front_flipper" type="revolute">
    <parent link="chassis"/>
    <child link="right_front_flipper"/>
    <origin rpy="${PI/6} 0 0" xyz="${chassis_width/2+main_wheel_length+flipper_thickness/2} ${chassis_length/2} ${wheel_radius}"/>
    <axis xyz="1 0 0"/>
    <limit effort="5" lower="0" upper="${PI/2}" velocity="5"/>
  </joint>

   <link name="right_front_flipper">
    <inertial>
      <mass value="${flipper_mass}"/>
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <geometry>
        <box size="${flipper_thickness} ${flipper_length} ${flipper_width}"/>
      </geometry>
    </collision>
    <visual name="visual_1">
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <geometry>
        <box size="${flipper_thickness} ${flipper_length} ${flipper_width}"/>
      </geometry>
    </visual>

    <visual name="visual_2">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://ugvc_description/meshes/flipper_crawler.dae" />
        </geometry>
    </visual>
  </link>

  <joint name="left_front_flipper" type="revolute">
    <parent link="chassis"/>
    <child link="left_front_flipper"/>
    <origin rpy="${PI/6} 0 0" xyz="${-chassis_width/2-main_wheel_length-flipper_thickness/2} ${chassis_length/2} ${wheel_radius}"/>
    <axis xyz="1 0 0"/>
    <limit effort="5" lower="0" upper="${PI/2}" velocity="5"/>
  </joint>

   <link name="left_front_flipper">
    <inertial>
      <mass value="${flipper_mass}"/>
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <geometry>
        <box size="${flipper_thickness} ${flipper_length} ${flipper_width}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <geometry>
        <box size="${flipper_thickness} ${flipper_length} ${flipper_width}"/>
      </geometry>
    </visual>

    <visual name="visual_2">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://ugvc_description/meshes/flipper_crawler.dae" />
        </geometry>
    </visual>
  </link>

  <joint name="right_rear_flipper" type="revolute">
    <parent link="chassis"/>
    <child link="right_rear_flipper"/>
    <origin rpy="${-PI/6} 0 ${PI}" xyz="${chassis_width/2+main_wheel_length+flipper_thickness/2} ${-chassis_length/2} ${wheel_radius}"/>
    <axis xyz="1 0 0"/>
    <limit effort="5" lower="0" upper="${PI/2}" velocity="5"/>
  </joint>

   <link name="right_rear_flipper">
    <inertial>
      <mass value="${flipper_mass}"/>
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <geometry>
        <box size="${flipper_thickness} ${flipper_length} ${flipper_width}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <geometry>
        <box size="${flipper_thickness} ${flipper_length} ${flipper_width}"/>
      </geometry>
    </visual>

    <visual name="visual_2">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://ugvc_description/meshes/flipper_crawler.dae" />
        </geometry>
    </visual>
  </link>

  <joint name="left_rear_flipper" type="revolute">
    <parent link="chassis"/>
    <child link="left_rear_flipper"/>
    <origin rpy="${-PI/6} 0 ${PI}" xyz="${-chassis_width/2-main_wheel_length-flipper_thickness/2} ${-chassis_length/2} ${wheel_radius}"/>
    <axis xyz="1 0 0"/>
    <limit effort="5" lower="0" upper="${PI/2}" velocity="5"/>
  </joint>

   <link name="left_rear_flipper">
    <inertial>
      <mass value="${flipper_mass}"/>
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <geometry>
        <box size="${flipper_thickness} ${flipper_length} ${flipper_width}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="0 0 0" xyz="0 ${flipper_length/2} 0"/>
      <geometry>
        <box size="${flipper_thickness} ${flipper_length} ${flipper_width}"/>
      </geometry>
    </visual>

    <visual name="visual_2">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://ugvc_description/meshes/flipper_crawler.dae" />
        </geometry>
    </visual>
  </link>

  <joint name="right_front_flipper_wheel_1" type="continuous">
    <parent link="chassis"/>
    <child link="right_front_flipper_wheel_1"/>
    <origin rpy="0 0 ${PI}" xyz="${chassis_width/2+main_wheel_length+flipper_thickness+flipper_wheel_length/2} ${chassis_length/2} ${wheel_radius}"/>
    <axis xyz="1 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

  <link name="right_front_flipper_wheel_1">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <joint name="left_front_flipper_wheel_1" type="continuous">
    <parent link="chassis"/>
    <child link="left_front_flipper_wheel_1"/>
    <origin rpy="0 0 ${PI}" xyz="${-chassis_width/2-main_wheel_length-flipper_thickness-flipper_wheel_length/2} ${chassis_length/2} ${wheel_radius}"/>
    <axis xyz="1 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

  <link name="left_front_flipper_wheel_1">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>


  <joint name="right_front_flipper_wheel_2" type="continuous">
    <parent link="right_front_flipper"/>
    <child link="right_front_flipper_wheel_2"/>
    <origin rpy="0 0 ${PI}" xyz="${flipper_thickness/2+flipper_wheel_length/2} ${flipper_length} 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

  <link name="right_front_flipper_wheel_2">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <joint name="left_front_flipper_wheel_2" type="continuous">
    <parent link="left_front_flipper"/>
    <child link="left_front_flipper_wheel_2"/>
    <origin rpy="0 0 ${PI}" xyz="${-flipper_thickness/2-flipper_wheel_length/2} ${flipper_length} 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

  <link name="left_front_flipper_wheel_2">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

-->

<!--   rear flipper wheels    -->

<!-- by Kong 

  <joint name="right_rear_flipper_wheel_1" type="continuous">
    <parent link="chassis"/>
    <child link="right_rear_flipper_wheel_1"/>
    <origin rpy="0 0 ${PI}" xyz="${chassis_width/2+main_wheel_length+flipper_thickness+flipper_wheel_length/2} ${-chassis_length/2} ${wheel_radius}"/>
    <axis xyz="1 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

  <link name="right_rear_flipper_wheel_1">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <joint name="left_rear_flipper_wheel_1" type="continuous">
    <parent link="chassis"/>
    <child link="left_rear_flipper_wheel_1"/>
    <origin rpy="0 0 ${PI}" xyz="${-chassis_width/2-main_wheel_length-flipper_thickness-flipper_wheel_length/2} ${-chassis_length/2} ${wheel_radius}"/>
    <axis xyz="1 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

  <link name="left_rear_flipper_wheel_1">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>


  <joint name="right_rear_flipper_wheel_2" type="continuous">
    <parent link="right_rear_flipper"/>
    <child link="right_rear_flipper_wheel_2"/>
    <origin rpy="0 0 0" xyz="${-flipper_thickness/2-flipper_wheel_length/2} ${flipper_length} 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

  <link name="right_rear_flipper_wheel_2">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <joint name="left_rear_flipper_wheel_2" type="continuous">
    <parent link="left_rear_flipper"/>
    <child link="left_rear_flipper_wheel_2"/>
    <origin rpy="0 0 0" xyz="${flipper_thickness/2+flipper_wheel_length/2} ${flipper_length} 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

  <link name="left_rear_flipper_wheel_2">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <collision name="collision">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${flipper_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>
  by Kong -->

  <transmission name="right_main_front_wheel_trans" type="SimpleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="right_main_front_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="right_main_front_wheel">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
  </transmission>

  <transmission name="left_main_front_wheel_trans" type="SimpleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="left_main_front_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="left_main_front_wheel">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
  </transmission>

  <transmission name="right_main_rear_wheel_trans" type="SimpleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="right_main_rear_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="right_main_rear_wheel">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
  </transmission>


  <transmission name="left_main_rear_wheel_trans" type="SimpleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="left_main_rear_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="left_main_rear_wheel">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
  </transmission>

  <!--gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>100.0</updateRate>
      <robotNamespace>/</robotNamespace>
      <leftFrontJoint>left_main_front_wheel</leftFrontJoint>
      <rightFrontJoint>right_main_front_wheel</rightFrontJoint>
      <leftRearJoint>left_main_rear_wheel</leftRearJoint>
      <rightRearJoint>right_main_rear_wheel</rightRearJoint>
      <wheelSeparation>4</wheelSeparation>
      <wheelDiameter>0.1</wheelDiameter>
      <robotBaseFrame>chassis</robotBaseFrame>
      <torque>1</torque>
      <topicName>cmd_vel</topicName>
      <broadcastTF>0</broadcastTF>
    </plugin>
  </gazebo-->

</xacro:macro>>

 
</robot>